gitsindonesia/ui-component

packages/pagination/src/VPagination.stories.ts, packages/pagination/src/VPagination.vue
This allow users to customize contents for "First", "Last", "Previous" and "Next" button using `slots`, with fallback to default implementation of "<<", ">>", "<" and ">" respectively. 
usage will be something like this:
```
<pagination>
<template v:slot="btnFirst">First</template> // to customize "first" button content. Defaults to "<<"
<template v:slot="btnLast">Last</template> // to customize "last" button content. Defaults to ">>"
<template v:slot="btnPrev">Previous</template> // to customize "previous" button content. Defaults to "<"
<template v:slot="btnNext">Next</template> // to customize "next" button content. Defaults to ">"
</pagination>
```
=> feat(Pagination): allow custom content n for first, prev, next, last btn

packages/table/src/VDataTablePagination.stories.ts, packages/table/src/VDataTablePagination.vue
This allows users to pass `VPagination` slots into `VDataTablePagination` component, enabling user to further customize the component without whipping up their own custom component to make this work.
I've also updated the storybook docs to reflect these changes.
Usage will be something like this:
```
<VDataTablePagination>
<template v:slot="btnFirst">First</template> // to customize "first" button content. Defaults to "<<"
<template v:slot="btnLast">Last</template> // to customize "last" button content. Defaults to ">>"
<template v:slot="btnPrev">Previous</template> // to customize "previous" button content. Defaults to "<"
<template v:slot="btnNext">Next</template> // to customize "next" button content. Defaults to ">"
</VDataTablePagination>
```
=> support pagination slots

packages/table/src/VDataTable.stories.ts, packages/table/src/VDataTable.vue, packages/table/src/types.ts
This allows user to define specific classes for table columns (or `td`) through `tdClass` prop insider `header` definition.
```
// To apply specific class to td
const headers = [
{
value: 'index',
text: 'ID',
class: 'uppercase', // this will be applied to only header cell
tdClass: 'bold', // NEW: this will be applied to all cell in "index" column
},
{
value: 'name',
text: 'Name',
class: 'uppercase', // this will be applied to only header cell
tdClass: 'italic', // NEW: this will be applied to all cell in "name" column
},
]
```
=> feat: support custom td class for each column

docs/.vitepress/config.js, docs/components/card.md, packages/card/package.json, packages/card/src/VCard.stories.ts, packages/card/src/VCard.vue, packages/card/src/plugin.js, packages/tailwind-config/package.json, packages/tailwind-config/preset.js
- New tailwind plugin for card component
- New card docs
- New slots: `header.prepend` and `header.prepend`
=> feat(card): add tailwind plugin for card component

packages/table/src/VDataTable.vue
This should fix incorrect initial sort state on datatable component.
Previously, the component assumes that initial sort state is `asc` which is not always the case, causing possible mismatch between actual data being presented and the table state.
This fix set the sort initial to not make assumption of the state of initial data, letting dev to manually set the state through `sortBy` prop of the component if initial sort state is preferred.
=> fix(VDataTable); fix incorrect initial state for header state

packages/forms/src/input/VInputRange.stories.ts, packages/forms/src/input/VInputRange.vue
This PR fix issue in VInputRange where value changes are not being reflected by vee validate form values nor notified to parent outside component.
Now, to listen to value changes (outside vee-validate), people can use `input:modelValue` with value is an object formatted like this : `{min: 0, max:0}`.
The `Validation` story for this component has also been updated to properly show validation usage.
Note: This may introduce BREAKING CHANGES. As the `modelValue` is changed from `string` to `object` to make validating the values easier.
=> Pass change event to vee validate and v model

packages/app-bar/package.json, packages/collapsible/package.json, packages/forms/package.json, packages/icon/package.json, packages/layouts/package.json, packages/list/package.json, packages/menu/package.json, packages/menus/package.json, packages/modal/package.json, packages/multi-select/package.json, packages/nav-drawer/package.json, packages/navbar/package.json, packages/pages/package.json, packages/stats/package.json, packages/switch/package.json, packages/tabs/package.json, packages/toast/package.json, packages/ui/package.json
This merge fix issues with yarn in strict mode complaining about dependencies not being explicitly defined in packages.
this PR set :
- `@heroicons` and `@iconify` package as `peerDependencies`, requiring projects using `gits-ui` package to separately install these two libs along with `gits-ui` package.
- `@headlessui/vue` as `devDependencies`
=> chore: define missing dependencies

packages/forms/src/checkbox/VCheckbox.stories.ts, packages/forms/src/checkbox/VCheckbox.vue, packages/forms/src/form-select/VFormSelect.stories.ts, packages/forms/src/form-select/VFormSelect.vue, packages/forms/src/input/VInput.stories.ts, packages/forms/src/input/VInput.vue, packages/forms/src/input/VInputRange.stories.ts, packages/forms/src/input/VInputRange.vue, packages/forms/src/radio/VRadioGroup.stories.ts, packages/forms/src/radio/VRadioGroup.vue, packages/forms/src/textarea/Textarea.stories.ts, packages/forms/src/textarea/Textarea.vue
This changes would allow toggling between `eager` and `aggressive` mode of validation.
In `eager` mode, validation will only run on `submit`, `blur`. However when input state is invalid, it will run validation on `change` (`aggressive` mode), only reverting back if input is valid.
In `aggressive` mode, validation will run on `submit`, `blur`, and every `change`.
Implementation is taken from official docs [here](https://vee-validate.logaretm.com/v4/guide/composition-api/validation)
=> feat(Forms.VInput): add validationMode feature

docs/.vitepress/config.js, docs/components/spinner.md, packages/spinner/README.md, packages/spinner/src/VSpinner.stories.js
Added new entry in vuepress docs: `Spinner.`
I also updated storybook stories for `Spinner` component to be more concise by making size stories into one single story.
=> docs(Spinner): add vuepress entry for spinner component

docs/.vitepress/config.js, docs/components/stepper.md, packages/steppers/README.md, packages/steppers/src/Stepper.stories.ts
This PR add new docs entry in vuepress for `Stepper` component. This also fixed some issues `Stepper` storybook examples, such as implementation of vue router in stories causing active state not being applied.
=> Add vuepress entry for Stepper component

docs/components/stepper.md, packages/steppers/src/Stepper.stories.ts, packages/steppers/src/Stepper.vue
Added `linear` prop to `Stepper` component, allowing active state of step items to be treated as continuous instead of singular.
Also updated vuepress `Stepper` entry and add sample story for this feature.
=> feat(Stepper): add linear prop to enable continuous active state

packages/steppers/src/Stepper.vue, packages/steppers/src/StepperDivider.vue, packages/steppers/src/StepperItem.vue
Fix issue with stepper divider not appearing, or appearing with unexpected styling (incorrect location, incorrect width/height, etc).
This also added handling for `linear` state and improve style to reflect `active` state properly.
=> Fix issue stepper divider

packages/alert/package.json, packages/app-bar/package.json, packages/autocomplete/package.json, packages/badge/package.json, packages/breadcrumbs/package.json, packages/button/package.json, packages/collapsible/package.json, packages/dropdown/package.json, packages/forms/package.json, packages/icon/package.json, packages/layouts/package.json, packages/list/package.json, packages/menu/package.json, packages/menus/package.json, packages/modal/package.json, packages/multi-select/package.json, packages/nav-drawer/package.json, packages/navbar/package.json, packages/nuxt/package.json, packages/pages/package.json, packages/select/package.json, packages/services/package.json, packages/stats/package.json, packages/switch/package.json, packages/table/package.json, packages/tabs/package.json, packages/toast/package.json, packages/ui/package.json
Add missing peer deps declaration for `heroicons` and `iconify` in package that requires `icon` package.
These packages will require the two package above to be installed separately outside `@gits-id/ui` or `@gits-id/ui-nuxt`.
=> chore(deps): add heroicons and iconify to dependencies

packages/tabs/src/VTabs.vue
This fixes scroll issue happening in VTabs when `centerActive` is set to `true` or when `showArrows` is set to `true`.
=> Fix issue with scroll position in VTabs

docs/components/multi-select.md, packages/multi-select/src/VMultiSelect.stories.js, packages/multi-select/src/VMultiSelect.vue
This PR exposes `selection`, `max-selection`, `select-all` and `option item label` content as slot to accommodate custom rendering needs. Also created two slot position in option to enable prepend and appending custom to item list.
Storybook story and vuepress docs for this component has been updated to reflect these changes.
=> feat(multiselect): set some elements as slot to promote customization

docs/components/tabs.md, packages/tabs/src/VTab.vue, packages/tabs/src/VTabs.stories.ts, packages/tabs/src/VTabs.vue
This PR fixes issue with slider not resizing when tab width changes.
Also added a new slot `item` to allow customization for tab content (label) without overriding the actual tab rendering.
Existing slots is also improved when necessary, like passing the click handler on `previous` and `next` slot so user can just pass it to let VTab do whatever it needs to do if the node was not being override by user.
Docs for the component has also been improved. Adding new stories for slot customization in storybook, and add new entry in vuepress `VTab` entry or add more description/explanation/previews to existing docs.
=> [VTabs] fix slider issue and slot improvement

packages/forms/src/checkbox/VCheckbox.vue, packages/forms/src/input/VInput.vue, packages/forms/src/radio/VRadio.vue
This PR adjust:
- checkbox label behavior to match other forms label behavior, which is being hidden when label is not defined or empty.
- input and radio to have `errorClass` prop as implemented in other form inputs.
- input and checkbox to have `labelClass` prop as implemented in other form inputs
=> fix(forms): standardize label and error class

docs/components/stepper.md, packages/steppers/src/Stepper.stories.ts, packages/steppers/src/Stepper.vue
Add `clickable` prop to optionally allows `click` event to be emitted when user clicked on the step items.
Added new story to demonstrate how this prop works and updated the vuepress docs for this prop.
=> feat(stepper): add clickable prop

docs/components/select.md, packages/select/src/VSelect.stories.ts, packages/select/src/VSelect.vue
Related to [issue 81](https://github.com/gitsindonesia/ui-component/issues/81)
This PR change the underlying behavior of `VSelect` from relying on VeeValidate behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
=> feat(VSelect): refactor VSelect to be uncontrolled by default

docs/components/file-input.md, packages/forms/src/file-input/VFileUpload.stories.ts, packages/forms/src/file-input/VFileUpload.vue, packages/forms/src/file-input/VFileUploadButtonTheme.vue, packages/forms/src/file-input/VFileUploadDefaultTheme.vue, packages/forms/src/file-input/VFileUploadDropzoneTheme.vue, packages/forms/src/file-input/VFileUploadImageTheme.vue
feat(VFileUpload): added logic to show filename when input is set as multiple feat(VFileUploadImageTheme): added support for previewClass prop
docs(VFileUpload): add story to showcase customizing filename slot
This PR fixes issue with input not showing anything (no preview, no filename), when the component is defined with `multiple` prop.  This added logic to retrieve the filename of selected multiple files and also allow user to override said value through newly introduced `filename` slot.
To improve customization possibility, this PR also added support for `previewClass` when the component is defined as image.
This PR also add new story `Slot Filename` to demonstrate possible customization introduced by the newly added feature.
=> feat(VFileUpload): support slot to override filename display and filename on 'multiple' file input

packages/forms/src/checkbox/VCheckbox.stories.ts, packages/forms/src/checkbox/VCheckbox.vue
This PR change the underlying behavior of VCheckbox from relying on VeeValidate behavior and existence of modelValue prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
=> feat(VCheckbox): refactor to be uncontrolled by default

docs/components/textarea.md, packages/forms/src/textarea/Textarea.stories.ts, packages/forms/src/textarea/Textarea.vue
This PR added `labelClass` prop to provide similar usages as other fields.
This PR also change the underlying behavior of `Textarea` from relying on `VeeValidate` behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
- by using both `v-model` and `name` prop,
- and by using neither.
under two conditions: with and without VeeValidate `useForm` being defined in parent …
=> feat(Textarea): refactor to be uncontrolled by default + add labelClass prop

packages/forms/src/radio/VRadio.stories.ts, packages/forms/src/radio/VRadio.vue, packages/forms/src/radio/VRadioGroup.stories.ts, packages/forms/src/radio/VRadioGroup.vue
This PR change the underlying behavior of `VRadio` and `VRadioGroup` from relying on `VeeValidate` behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
- by using both `v-model` and `name` prop,
- and by using neither.
under two conditians: with and without VeeValidate `useForm` being defined in parent component.
=> feat(radio): refactor to be uncontrolled by default

docs/components/input.md, packages/forms/src/input/VInput.stories.ts, packages/forms/src/input/VInput.vue
This PR change the underlying behavior of `VInput` from relying on `VeeValidate` behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
This PR also remove unimplemented event of `blur` and `change` from `emit` declaration, allowing the fallthrough attribute to work as it should be for those events. Documentation has been updated to reflect this change too.
- by using …
=> feat(VInput): refactor to be uncontrolled by default

packages/forms/src/form-select/VFormSelect.stories.ts, packages/forms/src/form-select/VFormSelect.vue
This PR change the underlying behavior of `VFormSelect` from relying on VeeValidate behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
- by using both `v-model` and `name` prop,
- and by using neither.
under two conditions: with and without VeeValidate `useForm` being defined in parent component.
=> feat(VFormSelect): refactor to be uncontrolled by default

docs/components/radio-group.md, packages/forms/src/radio/VRadioGroup.stories.ts, packages/forms/src/radio/VRadioGroup.vue
This PR allows customization for radio group items depending on its state (selected or not) through `selectedClass` and `defaultClass` prop. Documentation has been updated and story has been added (title "Customization" to showcase the new props.
=> feat(VRadioGroup): add selectedClass and defaultClass to style radio

packages/multi-select/src/VMultiSelect.stories.ts, packages/multi-select/src/VMultiSelect.vue
This PR change the underlying behavior of `VMultiSelect` from relying on VeeValidate behavior and existence of `modelValue` prop being defined to behave similarly to uncontrolled inputs. This makes the component behavior more predictable and allow it to work without requiring specific stuff being setup in the environment that uses it.
- by using both `v-model` and `name` prop,
- and by using neither.
under two conditions: with and without VeeValidate `useForm` being defined in parent component.
=> feat(VMultiSelect): refactor to be uncontrolled by default

packages/forms/src/input/VInput.stories.ts, packages/forms/src/input/VInput.vue
#96 
This fix should resolve issues with clearable and initial value not working. `clerarable` now should clear the input value.
And initial value now will be honored. **However, when using VeeValidate, only `VInput` defined with `name` will have its initial value be affected by VeeValidate. Non-named inputs should either use `model-value` or `value` prop to initialize initialValue.**
I've updated the `TestInputState` story in storybook to show how the input works under different conditions.
=> fix(VInput): fix clearable and initial value not working

packages/select/src/VSelect.stories.ts, packages/select/src/VSelect.vue
This fix should resolve issues with clearable and initial value not working. `clerarable` now should clear the input value.
And initial value now will be honored. **However, when using VeeValidate, only `VSelect` defined with `name` will have its initial value be affected by VeeValidate. Non-named inputs should either use `model-value` or `value` prop to initialize initialValue.**
I've updated the `TestInputState` story in storybook to show how the input works under different conditions.
- [] I have linked an issue or discussion.
=> fix(VSelect): fix initial value not working

packages/forms/src/input/VInput.vue
This PR changes priority when setting initial value to v-model even when name prop exist and the component is under vee validate `form` .
=> fix(VInput): change initial priority to model value

docs/components/data-table.md, packages/table/src/VDataTable.stories.ts, packages/table/src/VDataTable.vue
This PR added support for multi-column sorting through `multiSort` prop and also fixes issues with header sort state not reflecting current sort state (previous to this PR, the UI gave impression that sort applied is multi column, despite not being so, and the sort direction also not relative to toggled column sort state).
NOTE: If `multiSort` is enabled (default is disabled), values emitted by `sortBy`, `sortDirection` and `sort` event will be sent as array instead of plain string. This is to prevent breaking changes to existing implementation.
=> feat(VDataTable): support multisort

packages/forms/src/ErrorMessage.vue, packages/forms/src/index.ts, packages/forms/src/input/VInput.vue
- new `hideError` prop on `VInput`
- new `ErrorMessage` component.
=> feat(Forms): add `hideError` prop on `VInput` and new `ErrorMessage` component

packages/autocomplete/package.json, packages/autocomplete/src/VAutocomplete.spec.ts, packages/autocomplete/src/VAutocomplete.vue, yarn.lock
Minta Validasi : 
- ( notFoundText ) keliatannya props ini ga kepake, karena udah ada noDataText
- Sekarang kalau misal search dan ga nemu apa yang di search, itu ga nampilin apa apa. Ada kondisi ketika filteredItems nya 0 dan variable query nya kosong, maka dia nampilin noDataText nya. 
Butuh konfirmasi apakaha memang seperti kondisinya ? Di commitan saya ini, aku ada ngehapus kondisi `&& query === ''` nya. Agar ketika search dan ga nemuin yang dicari, harusnya `noDataText` nya muncul. Ini harusnya ke fix di sini : https://github.com/gitsindonesia/ui-component/commit/f1530ec12357122a1e20db6892dd946860e4ef09
- Lalu ada beberapa test yang aku skip : 
1. Ketika `query` nya kosong, itu nampilin semua items. Tapi ketika di write codingannya. Ternyata muncul error
2. Ketika `clearable true` …
=> test(VAutoComplete): add unit testing VAutoComplete component

docs/components/modal.md, docs/guide/customization.md, packages/modal/src/Modal.vue, packages/modal/src/ModalBody.vue, packages/modal/src/ModalFooter.vue, packages/modal/src/ModalHeader.vue, packages/modal/src/ModalTitle.vue, packages/modal/src/VModal.stories.ts, packages/modal/src/VModal.vue, packages/modal/src/index.ts, packages/themes/src/morpheme/_modal.scss, packages/ui/src/index.ts
This PR introduced a new declarative approach to use the modal component, providing you with enhanced flexibility. This approach involves breaking down the modal component into five separate components, each serving a specific purpose. To utilize this feature, you will need to manually import these components.
The modal components are as follows:
- `Modal`
-   `ModalHeader`
-   `ModalTitle`
-   `ModalBody`
-   `ModalFooter`
Unlike before, these components are not auto-imported. Therefore, you must import them individually based on your requirements.
Here's a brief overview of each modal component and its purpose:
- `Modal`: This is the main component that serves as the container for the entire modal dialog.
- `ModalHeader`: Use this component to display the header section of the modal. …
=> feat(Modal): add new declarative modal components

packages/select/src/VSelect.vue
- Change headless UI usage to `Combobox` component
- Fix issue can't space when `searchable`
=> fix(Select): change headless UI usage to `Combobox` component & fix issue can't space when `searchable`

packages/forms/src/checkbox/Checkbox.vue, packages/forms/src/form-select/Select.vue, packages/forms/src/input/Input.vue, packages/forms/src/radio/Radio.vue, packages/forms/src/textarea/Textarea.vue
This PR changes default value for `name` and `id` prop to `undefined` from previously empty string (`""`) for non-vee-validate form components.
This will prevent empty `id` prop from being "rendered" and trip Vue, when the user initialized components without explicitly setting `name` or `id` prop, causing numerous warning about _duplicate id_ being found.
=> fix: change `id` prop default to `undefined`

packages/forms/src/form-select/Select.vue, packages/forms/src/input/Input.vue
- [ x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Pass `name` prop to native html form element (select and input) explicitly, as this prop is listed explicitly as component props, thus not automatically inherited when psasing `v-bind="$attrs"` to the native html element.
This would fix issue where using the input value is not retrievable from `<form>` element due to missing `name` prop in actual HTML tree, even when `name` is actually defined when creating the element in vue. For example is the case below:
```
// form.vue
<template>
<form @submit="onSubmit">
<Input name="input1" />
<input name="htmlinput" />
</form>
</template>
<script setup lang="ts">
import {Input} from '@morpheme/forms';
const onSubmit = (evt) => {
const fd = new FormData(evt.target); …
```
=> fix(forms): missing name prop
