gitsindonesia/ui-component

packages/table/src/VDataTable.stories.ts, packages/table/src/VDataTable.vue
This allows user to define classes to apply to table rows through `trClass` prop.
```
// To apply custom class to table row (tr)
<v-data-table
tr-class="hover:bg-blue-700 hover:text-white"
/>
```
=> feat: support custom tr class

packages/app-bar/src/VAppBar.spec.ts, packages/app-bar/src/VAppBar.vue, packages/theme/defaultTheme.ts
- add `defaultShadows` constant to `@gits-id/theme/defaultTheme`
- Improve app-bar test
=> feat(app-bar): improve app-bar typings

docs/.vitepress/config.js, docs/components/badge.md, packages/app-bar/src/plugin.js, packages/badge/package.json, packages/badge/src/VBadge.stories.ts, packages/badge/src/VBadge.vue, packages/badge/src/plugin.js, packages/stats/src/VStats.vue, packages/tailwind-config/package.json, packages/tailwind-config/preset.js, packages/theme/defaultTheme.ts, packages/ui/src/snippets/Navbar/Navbar.vue
- add tailwind plugin for badge
- add new badge docs
=> feat(badge): revamp badge component

docs/.vitepress/config.js, docs/components/tabs.md, docs/components/tooltip.md
Add docs for Tabs and Tooltip components.
=> docs: tabs and tooltip

docs/.vitepress/config.js, docs/components/modal.md, docs/components/multi-select.md
- feat: add documentation modal component
- feat: add documentation multi select component
=> feat: add documentation modal & multi select components

docs/components/progress-bar.md, packages/forms/src/form-select/types.ts, packages/progress/src/VProgressBar.stories.ts, packages/progress/src/VProgressBar.vue
Revamp `VProgressBar` component:
- Added CSS Properties
- New `indeterminate` style
- `v-model` support
- Accessibility support
- Update docs
**BREAKING CHANGE:**
- Changed value prop from `width` to `modelValue`
=> feat(VProgressBar): revamp `VProgressBar` component

.storybook/preview-head.html, docs/components/button.md, packages/button/src/VBtn.stories.ts, packages/button/src/VBtn.vue, packages/button/src/VBtnGroup.vue, packages/button/src/VBtnToolbar.vue, packages/button/src/index.ts, packages/nuxt/src/module.ts, packages/tailwind-components/src/button.js
- New components: `VBtnGroup` and `VBtnToolbar`
- Update button sizes
=> feat(Button): add `VBtnGroup` and `VBtnToolbar` component

docs/components/pagination.md, packages/pagination/README.md, packages/pagination/src/VPagination.stories.ts, packages/pagination/src/VPagination.vue, packages/pagination/src/VPaginationItem.vue, packages/pagination/src/index.ts, packages/pagination/src/types.ts, packages/table/src/VDataTable.vue
- Add CSS Properties
- More customizable
- 3 sizes: sm, md, lg
- New `flat` style
=> feat(Pagination): revamp Pagination component

docs/components/tabs.md, packages/nuxt/src/module.ts, packages/tabs/README.md, packages/tabs/src/VTab.vue, packages/tabs/src/VTabs.stories.ts, packages/tabs/src/VTabs.vue, packages/tabs/src/VTabsSlider.vue, packages/tabs/src/index.ts
- more customizable via CSS Properties
- new `VTabsSlider` component
- implement default colors: `primary`, `secondary`, `info`, `warning`, `error`
- experimental: inject/provide for default slots
- update docs
- update storybook
- Fix #50
=> feat(VTabs): improved tabs component

docs/components/toast.md, packages/toast/README.md, packages/toast/package.json, packages/toast/src/VToast.stories.ts, packages/toast/src/VToast.vue, packages/toast/src/types.ts
- Remake toast component for more flexible
- Added default styles. No tailwind is required
- Update toast docs
- Lighter component. No more dependency on `@headlessui/vue`
- Lots of old props deprecated. Check out the docs for more info
=> feat(VToast): revamp toast component

docs/.vitepress/config.js, docs/components/switch.md, packages/switch/README.md, packages/switch/package.json, packages/switch/src/VSwitch.stories.ts, packages/switch/src/VSwitch.vue
- Add CSS Properties
- Add Docs
- Update Storybook
=> feat(VSwitch): customizable switch with CSS Properties

packages/list/README.md, packages/list/src/List.css, packages/list/src/List.stories.ts, packages/list/src/List.vue, packages/list/src/ListItem.vue, packages/list/src/ListItemDivider.vue, packages/list/src/ListItemHeader.vue, packages/list/vite.config.js
- Add CSS Properties support
- New divider `inset` style
- New `dense` and `small` style
- New props: `shaped`, `rounded`, `tile`, `flush`, and `hover` on the `VList` component. This will allow to change list item style from VList component
=> feat(VList): revamp VList component

docs/components/data-table.md, packages/forms/src/checkbox/VCheckbox.stories.ts, packages/forms/src/checkbox/VCheckbox.vue, packages/table/src/VDataTable.stories.ts, packages/table/src/VDataTable.vue
- Deprecated `value` props. Use `modelValue` instead
- Add some new CSS Properties
- `VCheckbox`: fix multiple checkbox issues
- Add new event `row:click`
- Update storybook
- Update docs
=> feat(VDataTable): improved `VDataTable` component

docs/components/tabs.md, packages/tabs/src/VTab.vue, packages/tabs/src/VTabs.stories.ts, packages/tabs/src/VTabs.vue
fix(tabs): handle removable prop effect in component instead of just emitting event
refactor(tabs): move remove icon from VTab to VTabs
docs(tabs): update docs for source code in storybook
docs(tabs): add new info related to remove icon in vuepress entry
=> feat(tabs): handle removable effect

docs/components/modal.md, packages/modal/src/VModal.css, packages/modal/src/VModal.stories.ts, packages/modal/src/VModal.vue
- New props: `title-class`, `width` and `max-width`
- New `close` slot prop on `footer`
- New CSS Properties
- Improved Docs
=> feat(VModal): more customizable modal

docs/.vitepress/config.js, docs/components/app-bar.md, docs/components/autocomplete.md, docs/components/avatar.md, docs/components/badge.md, docs/guide/customization.md, docs/guide/introduction.md, docs/guide/nuxt.md, docs/guide/starter.md, docs/guide/theme.md, docs/index.md
The docs is improved with the help of ChatGPT 😄
=> docs: improve docs

docs/components/multi-select.md, packages/multi-select/src/VMultiSelect.stories.ts, packages/multi-select/src/VMultiSelect.vue
Add proper handling for disabled and readonly state in `VMultiSelect` component.
Also moved the component entry in storybook to under `Forms`.
=> feat(multiselect): add disabled and readonly feature

.gitignore, docs/components/data-table-pagination.md, package.json, packages/select/src/VSelect.vue, packages/table/package.json, packages/table/src/VDataTablePagination.scss, packages/table/src/VDataTablePagination.stories.ts, packages/table/src/VDataTablePagination.vue, yarn.lock
#81 
- Replace `VSelect` with the basic HTML `<select>`
- Add SASS styles for VDataTablePagination
- Deprecate event: `update:perPage`. Use `update:itemsPerPage` instead.
- **VSelect**: fix selected text when return-object
=> feat(VDataTablePagination): replace VSelect with HTML select & add SASS

.storybook/preview.js, packages/nav-drawer/src/NavDrawer.mdx, packages/nav-drawer/src/NavDrawer.stories.ts, stories/foundation/colors/Colors.vue
None.
- Fix styles not loaded in the storybook
- Fix storybook build
=> fix: fix build & styles not loaded in storybook

docs/roadmap.md, packages/select/src/VSelect.stories.ts, packages/select/src/VSelect.vue
#95 
- lookup selected text from original items
- clear search input when selected
=> fix(VSelect): lookup selected text from original items & clear search input when selected

packages/nuxt/package.json, packages/nuxt/playground/app.vue, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/playground/tailwind.config.js, packages/nuxt/src/module.ts
- improve auto-imports components. Now, it will auto-import the `.vue` component instead of the bundled one.
- added new option: `loadFloatingVueStyles` with default value `true`
- change default value of `css` option to `false`
=> feat(nuxt): improve auto-imports components

packages/autocomplete/package.json, packages/autocomplete/src/VAutocomplete.stories.ts, packages/autocomplete/src/VAutocomplete.vue, packages/forms/src/checkbox/VCheckbox.vue, packages/forms/src/composables/index.ts, packages/forms/src/composables/useFormValue.ts, packages/forms/src/file-input/VFileUpload.vue, packages/forms/src/form-select/VFormSelect.vue, packages/forms/src/index.ts, packages/forms/src/input/VInput.stories.ts, packages/forms/src/input/VInput.vue, packages/forms/src/input/VInputGroup.vue, packages/forms/src/radio/VRadio.vue, packages/forms/src/radio/VRadioGroup.vue, packages/forms/src/textarea/Textarea.vue, packages/multi-select/src/VMultiSelect.vue, packages/select/src/VSelect.vue
#103 
- refactor uncontrolled value logic into `useFormValue` composable
- fix #103 
- deprecate `value` prop on form component. use `modelValue` instead
=> fix(Forms): refactor uncontrolled value logic into `useFormValue` composable

docs/.vitepress/config.js, docs/guide/nuxt.md, packages/nuxt/playground/app.vue, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/src/module.ts, packages/tabs/src/VTabs.vue
- fix: load required styles when not using CSS or SASS bundle
- feat: add new `loadDefaultStyles` option with default value `true`
- feat: ad module option docs block
- docs: update nuxt docs
- additional: fix(SSR): fix undefined MutationObserver on VTabs when in SSR mode
=> fix(nuxt): load required styles when not using CSS or SASS bundle

packages/app-bar/src/VAppBar.scss, packages/autocomplete/src/VAutocomplete.stories.ts, packages/modal/src/VModal.vue
- fix: optional `width` and `maxWidth` in `VModal` & fix transition value in `VAppBar`
=> fix: optional `width` and `maxWidth` in `VModal` & fix transition value in `VAppBar`

packages/menus/src/VMenus.vue, packages/nuxt/playground/app.vue
- fix(VMenus): fix floating vue extend options
=> fix(VMenus): fix floating vue extend options

packages/autocomplete/src/VAutocomplete.scss, packages/autocomplete/src/VAutocomplete.vue
- fix(VAutocomplete): fix missing `selected` property
- fix(VAutocomplete): fix missing `clear` event
- fix(VAutocomplete): fix missing error color variable
=> fix(VAutocomplete): fix undefined variable, missing css properties, & `clear` event

docs/components/dropdown.md, packages/dropdown/src/Dropdown.dark.scss, packages/dropdown/src/Dropdown.scss, packages/dropdown/src/Dropdown.stories.ts, packages/dropdown/src/Dropdown.vue, packages/dropdown/src/DropdownItem.vue
- improved CSS Properties
- add new `prefixIcon` props for adding prefix icon before label
- add new `nuxt` props for rendering item as NuxtLink
=> feat(VDropdown): improve VDropdown CSS Properties and add new props

docs/components/input.md, packages/forms/src/forms.scss, packages/forms/src/input/VInput.stories.ts, packages/forms/src/input/VInput.vue
- feat(VInput): add new `rounded` style
=> feat(VInput): add new `rounded` style

packages/nuxt/package.json, starter/nuxt-admin/package.json, starter/nuxt-admin/yarn.lock, starter/nuxt-auth/package.json, starter/nuxt-auth/yarn.lock, starter/nuxt-minimal/package.json, starter/nuxt-minimal/yarn.lock, yarn.lock
=> feat(nuxt): upgrade to nuxt 3.1.1

packages/forms/src/radio/VRadio.dark.scss, packages/forms/src/radio/VRadio.scss, packages/forms/src/radio/VRadio.stories.ts, packages/forms/src/radio/VRadio.vue, packages/forms/src/radio/VRadioGroup.dark.scss, packages/forms/src/radio/VRadioGroup.scss, packages/forms/src/radio/VRadioGroup.stories.ts, packages/forms/src/radio/VRadioGroup.vue, packages/nuxt/playground/app.vue, packages/ui/src/style.dark.scss
#116 
Fix and improve dark mode for VRadio and VRadioGroup.
=> fix(VRadio & VRadioGroup): fix and improve dark mode for VRadio and VRadioGroup

docs/components/app-bar.md, packages/app-bar/src/VAppBar.stories.ts, packages/app-bar/src/VAppBar.vue
Add `elevate-on-scroll` and `hide-on-scroll` features.
=> feat(VAppBar): add `elevate-on-scroll` and `hide-on-scroll` features

docs/.vitepress/config.js, docs/components/bottom-sheet.md, packages/bottom-sheets/CHANGELOG.md, packages/bottom-sheets/README.md, packages/bottom-sheets/package.json, packages/bottom-sheets/postcss.config.js, packages/bottom-sheets/src/BottomSheet.dark.scss, packages/bottom-sheets/src/BottomSheet.scss, packages/bottom-sheets/src/BottomSheet.stories.ts, packages/bottom-sheets/src/BottomSheet.test.ts, packages/bottom-sheets/src/BottomSheet.vue, packages/bottom-sheets/src/BottomSheetBody.vue, packages/bottom-sheets/src/BottomSheetFooter.vue, packages/bottom-sheets/src/BottomSheetHeader.vue, packages/bottom-sheets/src/BottomSheetMenus.vue, packages/bottom-sheets/src/BottomSheetOverlay.vue, packages/bottom-sheets/src/index.ts, packages/bottom-sheets/src/types.ts, packages/bottom-sheets/stories/Changelog.stories.mdx, packages/bottom-sheets/stories/Readme.stories.mdx, packages/bottom-sheets/tailwind.config.js, packages/bottom-sheets/tsconfig.json, packages/bottom-sheets/vite.config.js, packages/nuxt/playground/app.vue, packages/nuxt/src/module.ts, packages/ui/package.json, packages/ui/src/index.ts, packages/ui/src/style.dark.scss, packages/ui/src/style.scss
Add new `VBottomSheet` components.
=> feat(VBottomSheet): add new bottom sheet component

docs/.vitepress/config.js, docs/components/rating.md, packages/nuxt/src/module.ts, packages/rating/CHANGELOG.md, packages/rating/README.md, packages/rating/package.json, packages/rating/postcss.config.js, packages/rating/src/AlphaColor.ts, packages/rating/src/Rating.scss, packages/rating/src/Rating.stories.ts, packages/rating/src/Rating.vue, packages/rating/src/RatingStar.vue, packages/rating/src/index.ts, packages/rating/stories/Changelog.stories.mdx, packages/rating/stories/Readme.stories.mdx, packages/rating/tailwind.config.js, packages/rating/tsconfig.json, packages/rating/vite.config.js, packages/ui/package.json, packages/ui/src/index.ts
Add new `VRating`: rating component.
=> feat(VRating): new rating component

docs/components/bottom-sheet.md, packages/bottom-sheets/src/BottomSheet.scss, packages/bottom-sheets/src/BottomSheet.stories.ts, packages/bottom-sheets/src/BottomSheet.vue, packages/bottom-sheets/src/BottomSheetHandle.vue, packages/bottom-sheets/src/index.ts, packages/bottom-sheets/src/types.ts, packages/nuxt/src/module.ts, packages/ui/src/index.ts
=> feat(Bottom Sheet): add bottom sheet handle

docs/components/app-bar.md, packages/app-bar/src/VAppBar.scss, packages/app-bar/src/VAppBar.stories.ts, packages/app-bar/src/VAppBar.vue
feat(VAppBar): new `auto` size.
=> feat(VAppBar): new `auto` size

packages/ui/package.json, packages/ui/src/index.ts
=> feat(ui): register stepper components

packages/nav-drawer/src/NavDrawer.scss
=> fix(NavDrawer): fix default shadow value

packages/nuxt/src/module.ts
Nuxt: fix `VMenuIcon` export path.
=> fix(nuxt): fix `VMenuIcon` export path

packages/alert/src/VAlert.spec.ts
- add unit testing alert component (100%)
=> test(VAlert): add unit testing alert component

packages/autocomplete/src/VAutocomplete.stories.ts, packages/autocomplete/src/VAutocomplete.vue, packages/editor/src/VEditor.stories.ts, packages/editor/src/VEditor.vue, packages/forms/src/checkbox/VCheckbox.stories.ts, packages/forms/src/checkbox/VCheckbox.vue, packages/forms/src/file-input/VFileUpload.vue, packages/forms/src/input/VInputRange.stories.ts, packages/forms/src/input/VInputRange.vue, packages/forms/src/textarea/Textarea.stories.ts, packages/forms/src/textarea/Textarea.vue, packages/multi-select/src/VMultiSelect.stories.ts, packages/multi-select/src/VMultiSelect.vue, packages/quill-editor/src/VQuillEditor.stories.ts, packages/quill-editor/src/VQuillEditor.vue, packages/select/src/VSelect.stories.ts, packages/select/src/VSelect.vue
Add the ability to hide error messages via `hideError` prop.
=> feat(Forms): add the ability to hide error messages via `hideError` prop

packages/multi-select/src/VMultiSelect.stories.ts, packages/multi-select/src/VMultiSelect.vue
#133 
Fix bug error when clearing the value.
=> fix(VMultiSelect): fix bug error when clearing value

packages/quill-editor/src/VQuillEditor.vue
Fix(VQuillEditor): disable auto fix cursor by default via `autoFixCursor` prop.
=> fix(VQuillEditor): disable auto fix cursor by default via `autoFixCursor` prop

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> ci: use action@checkout v3

packages/app-bar/src/VAppBar.spec.ts
=> test(VAppBar): add unit testing VAppBar component

packages/quill-editor/src/VQuillEditor.vue
fix(VQuillEditor): make `label` prop optional.
=> fix(VQuillEditor): make `label` prop optional

packages/avatar/src/Avatar.spec.ts
=> test(VAvatar): add unit testing VAvatar component

packages/badge/src/VBadge.spec.ts
=> test(VBadge): add more unit testing on VBadge component

.storybook/preview.js, packages/table/src/VDataTable.dark.scss, packages/table/src/VDataTable.scss, packages/table/src/VDataTablePagination.dark.scss, packages/table/src/VDataTablePagination.scss
Fix load dependency styles when installed as an independent package.
=> fix(VDataTable): fix load dependency styles when installed as an independent package

packages/app-bar/src/VAppBar.stories.ts, packages/bottom-sheets/src/BottomSheet.stories.ts, packages/container/src/VContainer.stories.ts, packages/nav-drawer/src/deprecated/VNavDrawer.stories.ts, packages/navbar/src/VNavbar.stories.ts
=> chore: fix some storybook issues

packages/bottom-sheets/src/BottomSheet.dark.scss, packages/bottom-sheets/src/BottomSheet.scss, packages/bottom-sheets/src/BottomSheet.stories.ts
=> fix(VBottomSheet): import dependency styles

docs/guide/nuxt.md, packages/nuxt/src/module.ts
- New `optimizeDeps` option
- Optimize `yup` by default
=> feat(nuxt): add new `optimizeDeps` option

docs/guide/nuxt.md, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/src/module.ts
- Change option name from `gitsUi` to `morpheme`.
=> BREAKING CHANGE(nuxt)!: change option name to `morpheme`

docs/components/avatar.md, packages/avatar/package.json, packages/avatar/src/Avatar.scss, packages/avatar/src/Avatar.stories.ts, packages/avatar/src/Avatar.vue, packages/avatar/src/AvatarGroup.vue, packages/avatar/src/index.ts, packages/nuxt/src/module.ts
- New `VAvatarGroup` component
- Nuxt: auto-import `VAvatarGroup` component
- `VAvatar`: Allow default slot as initial avatar name
=> feat(Avatar): add new `VAvatarGroup` component

packages/alert/src/VAlert.vue
Improve alert accessibility by adding `role="alert".
=> fix(VAlert): improve alert accessibility

packages/text/package.json
=> fix(VText): fix package export

packages/alert/src/VAlert.spec.ts, packages/autocomplete/src/VAutocomplete.spec.ts, packages/breadcrumbs/src/VBreadcrumbs.spec.ts, packages/forms/src/checkbox/VCheckbox.spec.ts, packages/forms/src/input/VInput.spec.ts, packages/forms/src/input/VInputRange.spec.ts, packages/layouts/src/Auth.spec.ts, packages/layouts/src/Default.spec.ts, packages/logo/src/VLogo.spec.ts, packages/menu/src/VMenu.spec.ts, packages/nav-drawer/src/deprecated/VNavDrawer.spec.ts, packages/navbar/src/VNavbar.spec.ts, packages/navbar/src/VNavbar.vue, packages/pages/src/Login.spec.ts, packages/pages/src/NotFound.spec.ts, packages/switch/src/VSwitch.spec.ts
Add more testing for component and fix warning coverage
- VAutocomplete (98.03%)
- VSwitch (100%)
- VCheckbox (100%)
- VInput (99.32%)
=> test: add more testing component VAutocomplete VSwitch VCheckbox VInput, fix warning coverage

docs/components/navigation-drawer.md, packages/nav-drawer/src/NavDrawer.scss, packages/nav-drawer/src/NavDrawer.stories.ts, packages/nav-drawer/src/NavDrawer.vue, packages/nav-drawer/src/deprecated/Changelog.stories.mdx, packages/nav-drawer/src/deprecated/Readme.stories.mdx, packages/nav-drawer/src/types.ts
- Add new NavDrawer height variants
=> feat(VNavDrawer): add new NavDrawer height variants

docs/.vitepress/config.js, docs/components/progress-circular.md, packages/nuxt/playground/layouts/default.vue, packages/nuxt/playground/pages/index.vue, packages/nuxt/src/module.ts, packages/progress-circlular/CHANGELOG.md, packages/progress-circlular/README.md, packages/progress-circlular/package.json, packages/progress-circlular/postcss.config.js, packages/progress-circlular/src/VProgressCircular.spec.ts, packages/progress-circlular/src/VProgressCircular.stories.ts, packages/progress-circlular/src/VProgressCircular.vue, packages/progress-circlular/src/index.ts, packages/progress-circlular/src/vue.d.ts, packages/progress-circlular/tailwind.config.js, packages/progress-circlular/tsconfig.json, packages/progress-circlular/vite.config.js, packages/ui/package.json, packages/ui/src/index.ts, packages/ui/vite.config.js, packages/utils/helpers.ts, packages/utils/index.ts, packages/utils/morphemeColors.ts, packages/utils/package.json, vue.d.ts
- Add new `VProgressCircular` component
=> feat(VProgressCircular): add new `VProgressCircular` component

packages/icon/src/Icon.spec.ts, packages/icon/src/Icon.vue
Add `aria-hidden` attribute & add test.
=> feat(VIcon): add `aria-hidden` attribute & add test

packages/app-shell/src/VAppShell.test.ts, packages/avatar/src/AvatarGroup.test.ts, packages/bottom-sheets/src/BottomSheet.test.ts, packages/bottom-sheets/src/BottomSheet.vue, packages/breadcrumbs/src/VBreadcrumbs.spec.ts, packages/button/src/VBtn.spec.ts, packages/card/src/VCard.spec.ts, packages/collapsible/src/VCollapse.spec.ts
=> test: add more unit test

packages/button/src/VBtn.spec.ts
=> test(VBtn): add more test

packages/alert/src/VAlert.scss, packages/alert/src/VAlert.stories.ts, packages/alert/src/VAlertGroup.vue, packages/alert/src/index.ts
Add a new `VAlertGroup` component.
=> feat(Alert): add a new `VAlertGroup` component

docs/.vitepress/config.js, docs/components/banner.md, packages/banner/CHANGELOG.md, packages/banner/README.md, packages/banner/package.json, packages/banner/postcss.config.js, packages/banner/src/VBanner.scss, packages/banner/src/VBanner.stories.ts, packages/banner/src/VBanner.vue, packages/banner/src/VBannerText.vue, packages/banner/src/index.ts, packages/banner/src/stories/Changelog.stories.mdx, packages/banner/src/stories/Readme.stories.mdx, packages/banner/src/symbol.ts, packages/banner/src/vue.d.ts, packages/banner/tailwind.config.js, packages/banner/tsconfig.json, packages/banner/vite.config.js, packages/nuxt/src/module.ts, packages/ui/package.json, packages/ui/src/index.ts, packages/ui/src/style.scss
Add a new `VBanner` component.
=> feat(VBanner): add a new `VBanner` component

docs/components/navigation-drawer.md, packages/nav-drawer/src/NavDrawer.stories.ts, packages/nav-drawer/src/NavDrawer.vue, packages/themes/src/morpheme/_nav-drawer.scss
=> feat(NavDrawer): resizeable nav drawer

docs/components/data-table.md, packages/primitives/src/dialog/dialog.ts, packages/primitives/src/menu/index.ts, packages/table/src/VDataTable.stories.ts, packages/table/src/VDataTable.vue, packages/table/src/VDataTablePagination.stories.ts, packages/table/src/stories/BodySlotStory.vue, packages/table/src/stories/HeaderItemSlotStory.vue, packages/table/src/stories/HeaderSlotStory.vue, packages/table/src/stories/data.ts, packages/themes/src/morpheme/_data-table.scss
#184 
- New slots: `header`, `body` and `item`
- New props: `rowClass` and `itemClass`
- Change default `noDataText` prop value
- New table row / table column color variant: `v-table-tr--primary`, `v-table-tr--secondary`, `v-table-tr--info`, `v-table-tr--warning`, `v-table-tr--error` and `v-table-tr--dark`
- New table row class: `v-table-tr--odd` and `v-table-tr--even`
=> feat: DataTable enchancement

packages/table/src/VDataTable.vue, packages/table/src/stories/data.ts
This PR add new option by adding `disabled` key in items for disabled checkbox in table with selectable.
=> feat(table): add disabled option checkbox for table with selectable

packages/nuxt/package.json, packages/tooltip/vite.config.js, yarn.lock
fix floating-vue issue on nuxt 3.11.
=> fix(nuxt): fix floating-vue issue on nuxt 3.11
